/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package N;

import java.net.SocketException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author shanks
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        LoginBack = new java.awt.Panel();
        namefield = new javax.swing.JTextField();
        namelabel = new javax.swing.JLabel();
        iplabel = new javax.swing.JLabel();
        ipfield = new javax.swing.JTextField();
        portlabel = new javax.swing.JLabel();
        portfield = new javax.swing.JTextField();
        iplabel1 = new javax.swing.JLabel();
        iplabel2 = new javax.swing.JLabel();
        loginbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        LoginBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namefield.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        namefield.setForeground(new java.awt.Color(51, 51, 51));
        namefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefieldActionPerformed(evt);
            }
        });
        LoginBack.add(namefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 160, 20));

        namelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        namelabel.setForeground(new java.awt.Color(51, 51, 51));
        namelabel.setText("Name");
        LoginBack.add(namelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 60, 20));

        iplabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        iplabel.setForeground(new java.awt.Color(51, 51, 51));
        iplabel.setText("( eg:8192)");
        LoginBack.add(iplabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, 20));

        ipfield.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ipfield.setForeground(new java.awt.Color(51, 51, 51));
        ipfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipfieldActionPerformed(evt);
            }
        });
        LoginBack.add(ipfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 160, 20));

        portlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        portlabel.setForeground(new java.awt.Color(51, 51, 51));
        portlabel.setText("Port");
        LoginBack.add(portlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 40, 20));

        portfield.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        portfield.setForeground(new java.awt.Color(51, 51, 51));
        portfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portfieldActionPerformed(evt);
            }
        });
        LoginBack.add(portfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 160, 20));

        iplabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        iplabel1.setForeground(new java.awt.Color(51, 51, 51));
        iplabel1.setText("IP Address");
        LoginBack.add(iplabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 100, 20));

        iplabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        iplabel2.setForeground(new java.awt.Color(51, 51, 51));
        iplabel2.setText("eg(192.168.58:4430)");
        LoginBack.add(iplabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 140, 20));

        loginbutton.setBackground(new java.awt.Color(102, 102, 102));
        loginbutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loginbutton.setForeground(new java.awt.Color(51, 51, 51));
        loginbutton.setText("Login");
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });
        LoginBack.add(loginbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LoginBack, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginBack, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold

    private void namefieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void ipfieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void portfieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {

        String name=namefield.getText();
         String address=ipfield.getText();
          int port=Integer.parseInt(portfield.getText());
        login(name,address,port);        // TODO add your handling code here:
    }

    
    private void login(String name,String address,int port)
    {
        dispose();
        try {
            new ClientWindow(name,address,port);
        } catch (SocketException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private java.awt.Panel LoginBack;
    private javax.swing.JTextField ipfield;
    private javax.swing.JLabel iplabel;
    private javax.swing.JLabel iplabel1;
    private javax.swing.JLabel iplabel2;
    private javax.swing.JButton loginbutton;
    private javax.swing.JTextField namefield;
    private javax.swing.JLabel namelabel;
    private javax.swing.JTextField portfield;
    private javax.swing.JLabel portlabel;
    // End of variables declaration
}
