/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package N;


import java.awt.Color;
import java.net.SocketException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class RealLogin extends javax.swing.JFrame {
int xx,xy,flag=0;
    /**
     * Creates new form RealLogin
     */
    public RealLogin() {
        
        initComponents();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        namefield = new javax.swing.JTextField();
        ipad = new javax.swing.JLabel();
        ipfield = new javax.swing.JTextField();
        poort = new javax.swing.JLabel();
        portfield = new javax.swing.JTextField();
        loginpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cross = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel1MousePressed(evt);
            }
        });
        panel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel1MouseDragged(evt);
            }
        });
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nasirlogo.png"))); // NOI18N
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(51, 51, 51));
        name.setText("Username");
        panel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 70, 20));

        namefield.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        namefield.setForeground(new java.awt.Color(51, 51, 51));
        namefield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        panel1.add(namefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 170, 20));

        ipad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ipad.setForeground(new java.awt.Color(51, 51, 51));
        ipad.setText("IP Address");
        panel1.add(ipad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 93, 30));

        ipfield.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ipfield.setForeground(new java.awt.Color(51, 51, 51));
        ipfield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        ipfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipfieldActionPerformed(evt);
            }
        });
        panel1.add(ipfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 170, 20));

        poort.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        poort.setForeground(new java.awt.Color(51, 51, 51));
        poort.setText("Port");
        panel1.add(poort, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 44, -1));

        portfield.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        portfield.setForeground(new java.awt.Color(51, 51, 51));
        portfield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        panel1.add(portfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 170, 20));

        loginpanel.setBackground(new java.awt.Color(51, 51, 51));
        loginpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginpanelMouseExited(evt);
            }
        });
        loginpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        loginpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 60, 40));

        panel1.add(loginpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 250, 40));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("eg : 192.168.43.229");
        panel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("eg : 8192");
        panel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cross.setBackground(new java.awt.Color(255, 255, 255));
        cross.setForeground(new java.awt.Color(255, 255, 255));
        cross.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blackcross.png"))); // NOI18N
        cross.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        cross.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crossMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                crossMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                crossMouseExited(evt);
            }
        });
        jPanel1.add(cross, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 0, 30, 20));

        panel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 20));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel1MouseDragged
    int x=evt.getXOnScreen();
           int y=evt.getYOnScreen();

           this.setLocation(x-xx, y-xy);        // TODO add your handling code here:
    }//GEN-LAST:event_panel1MouseDragged

    private void panel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel1MousePressed
  xx=evt.getX();

        xy=evt.getY();
        // TODO add your handling code here:
    }//GEN-LAST:event_panel1MousePressed

    private void crossMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crossMouseClicked
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_crossMouseClicked

    private void crossMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crossMouseEntered
cross.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/darkred.png")));    // TODO add your handling code here:
    }//GEN-LAST:event_crossMouseEntered

    private void crossMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crossMouseExited
cross.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blackcross.png")));        // TODO add your handling code here:
    }//GEN-LAST:event_crossMouseExited

    private void loginpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginpanelMouseClicked
 String name=namefield.getText();
        String address=ipfield.getText();
        int port=Integer.parseInt(portfield.getText());
        login(name,address,port);              // TODO add your handling code here:
    }//GEN-LAST:event_loginpanelMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
 String name=namefield.getText();
        String address=ipfield.getText();
        int port=Integer.parseInt(portfield.getText());
        login(name,address,port);              // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void ipfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipfieldActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_ipfieldActionPerformed

    private void loginpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginpanelMouseEntered
loginpanel.setBackground(new Color(102,0,102));        // TODO add your handling code here:
    }//GEN-LAST:event_loginpanelMouseEntered

    private void loginpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginpanelMouseExited
loginpanel.setBackground(new Color(51,51,51));       // TODO add your handling code here:
    }//GEN-LAST:event_loginpanelMouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
loginpanel.setBackground(new Color(102,0,102));         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
    loginpanel.setBackground(new Color(51,51,51));    // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseExited


     private void login(String name,String address,int port)
    {
        dispose();
        try {
            new AwesomeClientWindow(name,address,port);
        } catch (SocketException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RealLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cross;
    private javax.swing.JLabel ipad;
    private javax.swing.JTextField ipfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel loginpanel;
    private javax.swing.JLabel name;
    private javax.swing.JTextField namefield;
    private java.awt.Panel panel1;
    private javax.swing.JLabel poort;
    private javax.swing.JTextField portfield;
    // End of variables declaration//GEN-END:variables
}
